var topics =
[
    [ "ADI (TriPort) C API", "group__c-adi.html", "group__c-adi" ],
    [ "ADI (TriPort) C++ API", "group__cpp-adi.html", "group__cpp-adi" ],
    [ "AI Vision Sensor C API", "group__c-aivision.html", "group__c-aivision" ],
    [ "AI Vision Sensor C++ API", "group__cpp-aivision.html", "group__cpp-aivision" ],
    [ "Extended API", "group__apix.html", "group__apix" ],
    [ "Colors C API", "group__c-colors.html", "group__c-colors" ],
    [ "C++ Color API", "group__cpp-colors.html", "group__cpp-colors" ],
    [ "VEX Generic Device C API (For Advanced Users)", "group__c-device.html", "group__c-device" ],
    [ "VEX Generic Device C++ API (For Advanced Users)", "group__cpp-device.html", "group__cpp-device" ],
    [ "VEX Distance Sensor C API", "group__c-distance.html", "group__c-distance" ],
    [ "VEX Distance Sensor C++ API", "group__cpp-distance.html", "group__cpp-distance" ],
    [ "ADI Expander C API", "group__ext-adi.html", "group__ext-adi" ],
    [ "VEX GPS Sensor C API", "group__c-gps.html", "group__c-gps" ],
    [ "VEX GPS Sensor C API", "group__cpp-gps.html", "group__cpp-gps" ],
    [ "VEX Inertial Sensor C API", "group__c-imu.html", "group__c-imu" ],
    [ "VEX Inertial Sensor C++ API", "group__cpp-imu.html", "group__cpp-imu" ],
    [ "VEX Link C API", "group__c-link.html", "group__c-link" ],
    [ "VEX Link C++ API", "group__cpp-link.html", "group__cpp-link" ],
    [ "Miscellaneous C API", "group__c-misc.html", "group__c-misc" ],
    [ "Miscellaneous C++ API", "group__cpp-misc.html", "group__cpp-misc" ],
    [ "Motors C++ API", "group__cpp-motor-group.html", "group__cpp-motor-group" ],
    [ "Motors C API", "group__c-motors.html", "group__c-motors" ],
    [ "Motors C++ API", "group__cpp-motors.html", "group__cpp-motors" ],
    [ "VEX Optical Sensor C API", "group__c-optical.html", "group__c-optical" ],
    [ "VEX Optical Sensor C++ API", "group__cpp-optical.html", "group__cpp-optical" ],
    [ "VEX Rotation Sensor C API", "group__c-rotation.html", "group__c-rotation" ],
    [ "VEX Rotation Sensor C++ API", "group__cpp-rotation.html", "group__cpp-rotation" ],
    [ "RTOS Facilities C API", "group__c-rtos.html", "group__c-rtos" ],
    [ "RTOS Facilities C++ API", "group__cpp-rtos.html", "group__cpp-rtos" ],
    [ "Simplified Brain Screen C API", "group__c-screen.html", "group__c-screen" ],
    [ "Simplified Brain Screen C++ API", "group__cpp-screen.html", "group__cpp-screen" ],
    [ "Generic Serial C API", "group__c-serial.html", "group__c-serial" ],
    [ "Generic Serial C++ API", "group__cpp-serial.html", "group__cpp-serial" ],
    [ "Vision Sensor C API", "group__c-vision.html", "group__c-vision" ],
    [ "Vision Sensor C++ API", "group__cpp-vision.html", "group__cpp-vision" ],
    [ "LLEMU C API", "group__c-llemu.html", "group__c-llemu" ],
    [ "LLEMU C++ API", "group__cpp-llemu.html", "group__cpp-llemu" ],
    [ "Cpp-abstract-motor", "group__cpp-abstract-motor.html", "group__cpp-abstract-motor" ]
];