# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
            
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup Python
      uses: actions/setup-python@v1.2.0
      with:
        python-version: 3.6
    - name: Pip Installer
      uses: BSFishy/pip-action@v1
      with:
        packages: jinja2 Pygments
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Move to m.css directory
      run: cd m.css/doucmentation
    - name: Run m.css
      run: ./doxygen.py
      
